.github/workflows/deploy-data.yml
.github/workflows/deploy-frontend.yml
.github/workflows/deploy-staging-data.yml
.github/workflows/deploy-staging-frontend.yml

fixed CI/CD pipeline

---

.github/workflows/deploy-data.yml
.github/workflows/deploy-staging-data.yml
data/package.json
data/src/build.ts
data/src/index.ts
data/src/utils/data.ts
frontend/.babelrc
frontend/firebase/firebase.json
frontend/package.json
frontend/src/apps/main/redux/actions/articles-scene/index.ts
frontend/src/apps/main/redux/actions/documentation-scene/index.ts
frontend/yarn.lock

Fixed async/await issue and improved data generator URLs

---

.github/workflows/deploy-data.yml
.github/workflows/deploy-staging-data.yml

fixed workflow bug for "generate" command

---

data/documentation/Advanced_Git_Commands/info.json
data/documentation/Getting_Started/content.md
data/documentation/Git_Basics/Collaboration_Scenarios/info.json
data/documentation/Git_Basics/info.json
data/documentation/list.json
frontend/package.json
frontend/src/apps/main/components/navbar/index.tsx
frontend/src/apps/main/components/navbar/style.scss
frontend/src/apps/main/entry/index.pug
frontend/src/apps/main/entry/index.tsx
frontend/src/apps/main/entry/webpack.plugins.js
frontend/src/apps/main/scenes/landing/header/style.scss
frontend/src/apps/main/scenes/landing/what-and-why/style.scss
frontend/src/apps/main/scenes/learn/content/index.tsx
frontend/src/apps/main/scenes/learn/content/style.scss
frontend/src/apps/main/scenes/learn/index.tsx
frontend/src/apps/main/scenes/learn/sidebar/index.tsx
frontend/src/apps/main/scenes/learn/sidebar/style.scss
frontend/src/apps/main/scenes/learn/style.scss
frontend/src/common/d.ts/__global.d.ts
frontend/src/common/style/_variables.scss
frontend/t9config.js
frontend/yarn.lock

Implementing #32 Learn Scene which has a Sidebar and a Content page, the last has: Hero image, Title, Description, Content(Markdown), Social Contact and Edit Button, and finally Comments 
Also, some UI tweaks across the website

32 develop learn scene

---

frontend/src/apps/main/scenes/articles/content/index.tsx
frontend/src/apps/main/scenes/articles/content/style.scss
frontend/src/apps/main/scenes/articles/index.tsx
frontend/src/apps/main/scenes/articles/sidebar/index.tsx
frontend/src/apps/main/scenes/articles/sidebar/style.scss
frontend/src/apps/main/scenes/articles/style.scss
frontend/src/apps/main/scenes/learn/sidebar/style.scss

Implemented Articles scene, where anyone can add he's article
implemented #33

📚 Implimented Articles scene

---

frontend/src/apps/main/components/footer/index.tsx
frontend/src/apps/main/components/footer/style.scss
frontend/src/common/style/_index.scss

add a footer to the landing page.
solve the horizontal overflow issue.
Fixes #55
Implements #53 
- [ x ] Affected `frontend`

add footer / fix overflow

---

frontend/src/apps/main/components/footer/index.tsx
frontend/src/apps/main/components/footer/style.scss
frontend/src/apps/main/entry/index.tsx

created a complete typed footer
Fixes #55 
Implements #53 
- [ x] Affected `frontend`

updated Footer Component

---

.github/workflows/deploy-data.yml
.github/workflows/deploy-frontend.yml
.github/workflows/deploy-staging-data.yml
.github/workflows/deploy-staging-frontend.yml
data/articles/ssr.json
data/documentation/ssr.json
data/projects/ssr.json
data/src/build.ts
data/src/index.ts
data/src/types/index.ts
data/yarn.lock
frontend/firebase/yarn.lock
frontend/src/apps/main/entry/index.pug
frontend/src/apps/main/entry/webpack.plugins.js
frontend/yarn.lock
fullstack/package.json
fullstack/src/utils/data.ts
fullstack/yarn.lock

dzCode.io now supports SSR!
- Added SSR collections for each model in data folder
- Refactored data and fullstack code
- Implemented SSR on build time for all URLs
- Updated Github Actions workflow to Deploy frontend on SSR collections change
- fixed string quotation on some workflow files
- upgraded dependencies
Implements #23

23 social media integration

---

.github/workflows/deploy-frontend.yml
.github/workflows/deploy-staging-frontend.yml
frontend/package.json

Added sitemap generation command
See also #23

🏗  added sitemap generation command

---

frontend/src/apps/main/entry/index.tsx
frontend/src/apps/main/scenes/learn/content/index.tsx
frontend/src/apps/main/scenes/projects/details/index.tsx

Fixed Contact Us url bug ( #103 )

🐞 fixed contact us url

---

api/functions/src/index.ts
frontend/src/apps/main/scenes/contact/form/index.tsx

fix double toast when submitting a message 
Fixes #73

fix double toast

---

frontend/src/apps/main/redux/actions/articles-scene/index.ts
frontend/src/apps/main/redux/actions/documentation-scene/index.ts
frontend/src/apps/main/redux/actions/projects-scene/index.ts

Fixed bug where accessing some URL that ends with `/` causes the page to stuck at loading
Fixes #111

🐞 fixed URL slug bug

---

.github/workflows/cgl-data.yml
.github/workflows/cgl-frontend.yml
.github/workflows/cgl-fullstack.yml

⚙️ updated CI job name to "Build-Check"

---

frontend/yarn.lock

🆙 updgraded packages

---

frontend/src/apps/main/redux/reducers/layout-reducer/index.ts

⁉️ added /FAQ link to navbar

---

frontend/package.json
frontend/src/apps/main/redux/actions/articles-scene/index.ts
frontend/src/apps/main/redux/actions/documentation-scene/index.ts
frontend/yarn.lock

🆙 upgraded j2t to v1.0.0

---

frontend/src/apps/main/entry/index.pug
frontend/src/apps/main/entry/index.tsx

🐞 fixed analytics bug

---

frontend/src/apps/main/components/footer/index.tsx
frontend/src/apps/main/entry/index.tsx

Pin footer to the bottom of the page
Fixes #143

143 fix footer positioning

---

data/articles/Send_Emails_With_Django_and_Gmail_A_Btter_Way/content.md
data/articles/Send_Emails_With_Django_and_Gmail_A_Btter_Way/info.json
data/articles/list.json
data/articles/ssr.json

add a new article send emails with Django and Gmail a better way to data/articles 
addresses #54

New article/send emails with django and gmail a better way

---

frontend/src/apps/main/components/markdown/index.tsx

Fixed image size in articles page #158

🐞 fixed images width in article page

---

frontend/package.json
frontend/src/apps/main/components/footer/index.tsx
frontend/src/apps/main/scenes/contact/index.tsx
frontend/src/apps/main/scenes/contact/style.scss

Make changes on UI dark mode to make it easy to read and write  and  also modified the content in the footer by adding the phone number and email.

Make changes on UI contact-us page

---

data/articles/The_Using_Of_Conventional_Commits_To_Contribute_To_DZCode/content.md
data/articles/The_Using_Of_Conventional_Commits_To_Contribute_To_DZCode/info.json
data/articles/list.json
data/articles/ssr.json
data/articles/top-articles.json

I added a new article about conventional commits which  is a new standard to write a readable commit message for your next project and contribution

New article/the using of conventional commits to contribute to dz code

---

.github/workflows/cgl-data.yml
.github/workflows/cgl-frontend.yml
.github/workflows/cgl-fullstack.yml
data/.eslintignore
data/.prettierignore
data/articles/Add_Your_Own_Article/content.md
data/articles/Send_Emails_With_Django_and_Gmail_A_Btter_Way/content.md
data/articles/Send_Emails_With_Django_and_Gmail_A_Btter_Way/info.json
data/articles/The_Using_Of_Conventional_Commits_To_Contribute_To_DZCode/content.md
data/articles/The_Using_Of_Conventional_Commits_To_Contribute_To_DZCode/info.json
data/articles/list.json
data/articles/ssr.json
data/eslint.eslintignore
data/package.json
frontend/.eslintignore
frontend/eslint.eslintignore
frontend/package.json
frontend/src/apps/main/entry/index.pug
fullstack/.eslintignore
fullstack/.prettierignore
fullstack/eslint.eslintignore
fullstack/package.json
package.json
yarn.lock

doing linting right

---

data/articles/A_Python_Website_No_Framework_Needed_PART_2/content.md
data/articles/A_Python_Website_No_Framework_Needed_PART_2/info.json
data/articles/list.json
data/articles/ssr.json

a new article to show how we can render an HTML template, and  handle post requests

New article/a python website no framework needed part 2

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/task.md
.github/PULL_REQUEST_TEMPLATE.md

- updated PR template
- cleaned bug and feature request template
- added task template

updated PR and Issue templates

---

data/articles/A_Python_Website_No_Framework_Needed/info.json
data/articles/A_Python_Website_No_Framework_Needed_PART_2/content.md

update article  title and content

Fix article ( using rebase )

---

README.md

Added documentation on how to add your own project
#166

🏗 added how to add reference your project

---

frontend/src/apps/main/components/navbar/index.tsx
frontend/src/apps/main/pages/faq/faq-Item/index.tsx
frontend/src/apps/main/pages/faq/index.tsx
frontend/src/apps/main/pages/faq/style.scss
frontend/src/apps/main/redux/reducers/faq-page/index.ts
frontend/src/apps/main/redux/reducers/layout-reducer/index.ts

- added frequently asked question & answers
- fix: first question open by default
- fix: remove search icon and add FAQ to navbar
Implements #181 
questions

faq questions

---

data/projects/DzCode/info.json
data/projects/Kuliya/info.json
data/projects/Leblad/info.json
data/projects/Project_1/info.json
data/projects/Project_2/info.json
data/projects/Project_3/info.json
data/projects/Project_4/info.json
data/projects/Project_5/info.json
data/projects/Project_6/info.json
data/projects/React_Project_Builder/info.json
data/projects/list.json
data/projects/ssr.json
data/projects/top-projects.json
frontend/src/apps/main/components/navbar/index.tsx
frontend/src/apps/main/pages/faq/faq-Item/index.tsx
frontend/src/apps/main/pages/faq/index.tsx
frontend/src/apps/main/pages/faq/style.scss
frontend/src/apps/main/redux/reducers/faq-page/index.ts
frontend/src/apps/main/redux/reducers/layout-reducer/index.ts

- ✅ fix :remove mock data & add all current projects
Implements #179

✅ fix : remove mock data & add all current projects

---

frontend/src/apps/main/components/footer/index.tsx
frontend/src/apps/main/redux/reducers/layout-reducer/index.ts

📚 update mock data and fix a contact title, padding issue
Implements #182

📚 update mock data

---

data/articles/A_Python_Website_No_Framework_Needed/info.json
data/articles/A_Python_Website_No_Framework_Needed_PART_2/info.json

fixed incorrect image url

---

frontend/src/apps/main/components/card/index.tsx

✅ fix: handle click event on card component

---

data/articles/How_To_Add_Your_Article_To_DzCode/info.json
data/articles/How_To_Add_Your_Project_To_DzCode/info.json
data/projects/Mishkal/info.json
data/projects/list.json
data/projects/ssr.json
data/projects/top-projects.json

📂 add mishkal project 
fix : article width image

📂 project : add mishkal

---

.github/workflows/code-coverage-report.yml
data/.eslintignore
data/.gitignore
data/.prettierignore
data/eslint.prettierignore
data/jest.config.js
data/package.json
data/src/config/index.spec.ts
frontend/.eslintignore
frontend/.gitignore
frontend/.prettierignore
frontend/eslint.prettierignore
frontend/jest.config.js
frontend/package.json
frontend/src/apps/main/components/SpeedDial/index.tsx
frontend/src/common/utils/index.spec.ts
frontend/src/common/utils/index.ts
fullstack/.eslintignore
fullstack/.gitignore
fullstack/.prettierignore
fullstack/eslint.prettierignore
fullstack/jest.config.js
fullstack/package.json
fullstack/src/config/index.spec.ts
package.json
yarn.lock

Added tests and Codecov test coverage
implements #135

Added test coverage

---

.github/PULL_REQUEST_TEMPLATE.md
.github/labeler.yml
.github/workflows/code-coverage-report.yml
README.md
frontend/src/common/utils/index.spec.ts

- updated PR template & removed redundant checks
- added github action labeler
- updated the table section in Readme

Made both Readme and PR more friendly

---

.github/workflows/deploy-data.yml
.github/workflows/deploy-frontend.yml
.github/workflows/deploy-staging-data.yml
.github/workflows/deploy-staging-frontend.yml

removed install --production

---

data/projects/Algerian_Administrative_Division/info.json
data/projects/list.json
data/projects/ssr.json

[AlgerianAdministrativeDivision ](https://github.com/mohsenuss91/AlgerianAdministrativeDivision) project added to [dzcode.io](https://github.com/dzcode-io) based on [dzcode.io article](https://www.dzcode.io/Articles/How_To_Add_Your_Project_To_DzCode/).

AlgerianAdministrativeDivision project added to dzcode.io

---

frontend/src/apps/main/redux/reducers/layout-reducer/index.ts

Social media links updated in Footer.

Social media links updated in Footer

---

api/package.json
api/src/controllers/github/index.ts
api/src/controllers/helloWorld.ts
api/src/routes/api/github/index.ts
api/src/routes/api/index.ts
api/src/routes/index.ts
api/src/services/github/index.ts
api/yarn.lock

Adding new endpoint to fetch the list of PR for dzcode.io
Implements #232 
temporary section -->

Added endoint giving recent PR of dzcode.io

---

data/projects/Flutter_Reaction_Button/info.json

Add Flutter reaction button package

---

data/articles/list.json
data/articles/ssr.json
data/articles/top-articles.json

Fixes `Open_source` article not shown

renamed Open_source to Open_source

---

data/projects/top-projects.json

Added **Algerian Administrative Division** project to the landing page
follow up on #225

added AAD project to landing page

---

data/articles/A_Python_Website_No_Framework_Needed/info.json
data/articles/A_Python_Website_No_Framework_Needed_PART_2/info.json
data/articles/How_To_Add_Your_Article_To_DzCode/info.json
data/articles/How_To_Add_Your_Project_To_DzCode/info.json
data/articles/Open_source/info.json
data/articles/Use_Conventional_Commits_To_Contribute_To_DZCode/info.json
data/projects/Algerian_Administrative_Division/info.json
data/projects/Kuliya/info.json
data/projects/Mishkal/info.json
data/projects/React_Project_Builder/info.json
frontend/src/apps/main/pages/landing/how-to-contribute/index.tsx
frontend/src/apps/main/pages/landing/what-and-why/index.tsx

This PR fixes various typos, missed punctuation and letter case.
Minor typos fixes
* I took the liberty to include fixes in articles descriptions (which I suppose would usually require original author's review) because I believe the changes did not affect the meaning and only dealt with language.

style front: fix typos & punctuation

---

data/models/projects/Algeria_Covid19_Tracker/content.md
data/models/projects/Algeria_Covid19_Tracker/info.json
data/models/projects/list.json
data/models/projects/ssr.json

🚀 Added Algeria COVID-19 Tracker (Front-End) Project

🚀 Added Algeria COVID-19 Tracker (Front-End) Project

---

api/src/controllers/github/index.ts
api/src/routes/api/github/index.ts
api/src/services/github/index.ts

create a list of Branches,Commits and  CountForks function.

add listBranches, listCommits and listForks

---

api/src/controllers/github/index.ts
api/src/routes/api/github/index.ts
api/src/services/github/index.ts

add two functions listWatchers,listIssues.

add two functions listWatchers,listIssues.

---

.github/workflows/check-data.yml
README.md
api/package.json
web/package.json
web/src/apps/main/components/navbar/ios-switch/index.tsx
web/src/apps/main/entry/index.pug
web/src/apps/main/redux/reducers/faq-page/faq.ts
yarn.lock

- Updated axios deps and removed @types/axios.
- fixed typo on yaml ci file.
- updated tutos links
- Fixed iOS switch style bug

fixing typos and upgrading deps

---

data/models/projects/React_Native_Currency_Converter/content.md
data/models/projects/React_Native_Currency_Converter/info.json
data/models/projects/list.json
data/models/projects/ssr.json

i've added my open source project that convert currency from DA to any other currency with real time bank exchange rate using React_Native with full screen responsive and both OS compatibility IOS / ANDROID .

📱 adding Project React_Native_Currency_Converter to dzcode.io/Projects

---

data/models/projects/Python_Complex/content.md
data/models/projects/Python_Complex/info.json
data/models/projects/list.json
data/models/projects/ssr.json

Hi, I'm happy to share my open source python package with you, I hope it will help all of you.

Add PythonComplex project 🦼

---

.github/labeler.yml
.github/workflows/labeler.yml
data/models/projects/List_to_Tree_aka_l2t/info.json
data/models/projects/list.json
data/models/projects/ssr.json

- added `l2t` npm library
- fixed labeler action ci

adding l2t and fixing labeler action

---

data/models/projects/Voice_Translator_React_Native/info.json
data/models/projects/list.json
data/models/projects/ssr.json

Adding my open source project app : ARAB to ENGLISH / ENGLISH to ARAB  using voice recognition technology

adding project : ARAB to ENGLISH / ENGLISH to ARAB 

---

web/package.json
web/src/apps/main/components/navbar/index.tsx
web/src/apps/main/components/navbar/lang-switch/index.tsx
web/src/apps/main/entry/app.tsx
web/src/apps/main/redux/index.ts
web/src/apps/main/redux/reducers/settings/index.ts
web/src/localization/index.tsx
web/src/localization/locals/ar.ts
web/src/localization/locals/en.ts
web/src/localization/locals/fr.ts
yarn.lock

This is a prototype MR implements  #24
The modification effects only navbar contents, once it works well, it could be generalized for entire front static contents 
Used tool : [react-intl](https://www.npmjs.com/package/react-intl)

First Localization implementation

---

web/src/apps/main/components/footer/index.tsx

Fix: copyright date auto-update

---

api/src/controllers/etc/index.ts
api/src/routes/api/index.ts

Implements #280
thanks for assigning issue to me! I created the root controller with some metadata. if you want to update somewhere, please don't hesitate and give me a feedback
- [ ✔️ ] New feature (non-breaking change which adds functionality)

Create root controller

---

api/src/index.ts
api/src/loaders/express-loader.ts
api/src/loaders/index.ts

Implements #277 
this PR is a part of improving api sources. I created `loaders` folder to isolate the initial tasks for running API server. 
if you think this is a not good method, you can refuse it !.! this is quite small thing so I just suggest carefully :)

Use loader

---

api/oracle-cloud/docker-compose.yml

This PR should fix cors error mentioned in #284 
just tested it on stage, this fixed it!
https://stage.dzcode.io/Learn/Getting_Started

Fix: load env variable from env file

---

web/src/apps/main/redux/actions/projects-page/index.ts

Shuffle projects

---

.github/PULL_REQUEST_TEMPLATE.md

Removed checkboxes from PR template, we will keep checkboxes only for specifying tasks

removed checkboxes from PR template

---

.github/ISSUE_TEMPLATE/task.md

we no longer use Zenhub, so removed all comments related to it

removed redundant Zenhub comment

---

web/src/apps/main/redux/index.ts

I've removed duplicate imports.

removed duplicate imports

---

web/src/apps/main/components/card/index.tsx

This fixes a visual bug on stage

changed Skeleton variant from circle to rect

---

data/models/projects/AiPalettes/info.json
data/models/projects/list.json

added AiPalettes

---

data/models/projects-v2/Dzair_Data_Usage/info.json

request to add dzair_data_usage 
dzair_data_usage  is a dart/flutter package for dealing with algerian cities data such as dairas,communes and more.
https://github.com/dfourcfive/dzair_data_usage

request to add a dart package

---

data/models/projects-v2/Algeria_Startup_Jobs/info.json

Added Algeria Startup Jobs project.

added ASJ project

---

api/src/app/middlewares/security.ts

This changes will allow you to run dzcode locally on other devices on the same router.

Fix: disabled CORS on dev environment

---

.github/workflows/check-api.yml
.github/workflows/check-common.yml
.github/workflows/check-data.yml
.github/workflows/check-mobile.yml
.github/workflows/check-web.yml
.github/workflows/coverage-report.yml
.github/workflows/deploy-to-production.yml
.github/workflows/deploy-to-stage.yml
mobile/App.tsx
mobile/src/components/shared/drawer-content.tsx
mobile/src/screens/articles/ui/articles-ui.tsx
mobile/src/screens/contribute/ui/contribute-ui.tsx
mobile/src/screens/faq/ui/faq-ui.tsx
mobile/src/screens/home/ui/home-ui.tsx
mobile/src/screens/learn/ui/learn-ui.tsx
mobile/src/screens/projects/ui/projects-ui.tsx
mobile/src/styles/colors.ts
mobile/src/styles/global-styles.ts

This PR will allow us to deploy Over-The-Air updates when creating Github Releases (stage-only releases for mobile for now)
- it also contin fixes for the color palette, to demonstrate publishing OTA updates

Feature: deploy mobile to stage

---

api/oracle-cloud/Dockerfile

Fixes [stuck action](https://github.com/dzcode-io/dzcode.io/runs/3155530325?check_suite_focus=true) due to postinstall script.

Bugfix: skipped postinstall script when deploying api

---

data/models/projects-v2/Moadaly/info.json
data/models/projects-v2/STRM_Test/info.json

Added projects:
- strm test
- moadaly

Add two projects

---

package.json

removed redundant pre-commit script for mobile

---

web/.babelrc.js
web/.eslintrc.js
web/package.json
web/src/apps/main/components/authors/index.tsx
web/src/apps/main/components/card/index.tsx
web/src/apps/main/components/contributors/index.tsx
web/src/apps/main/components/speed-dial/index.tsx
web/src/apps/main/components/theme/index.tsx
web/src/apps/main/entry/index.tsx
web/src/apps/main/pages/articles/landing/index.tsx
web/src/apps/main/pages/learn/landing/index.tsx
web/src/apps/main/pages/projects/catalog/index.tsx
yarn.lock

- Add the plug-in to './web' and remove all effected code
- disable 'react/prop-types' eslint rule
fixes #343

Chore: add runtime prop-types checking

---

web/package.json
web/src/apps/main/entry/index.tsx
yarn.lock

Setup sentry for error logging on web 
resolves #351 

Feature: Setup Sentry for error logging on web

---

api/package.json
api/src/app/index.ts
yarn.lock

Setup sentry for error logging on api 
resolves #351 

Feature: Setup Sentry for error logging on api

---

mobile/App.tsx
mobile/app.json
mobile/babel.config.js
mobile/package.json
yarn.lock

Setup sentry for error logging on mobile 
resolves #351 

Feature: Setup Sentry for error logging on mobile

---

api/src/app/index.ts
mobile/App.tsx
web/src/apps/main/entry/index.tsx

A followup PR to #351 to set up  Sentry environment to be either: production, staging or development

Chore: properly setup Sentry environment

---

api/src/app/index.ts
api/src/github/service.ts
api/src/team/controller.ts
api/src/team/repository.ts
common/src/types/api-responses.ts

Feature: team page backend part

---

data/models/projects-v2/React_Help_Create/info.json

Adding a new open source project 🤖
- I'm not sure

Adding react-help-create project

---

mobile/app.json
mobile/src/redux/actions/general/index.ts

This PR fixes #367 as well as weird theme switching behaviour when switching out of and back to the app.

Bugfix: System Theme detection not working properly

---

api/src/github/service.ts
api/src/team/controller.ts
api/src/team/repository.ts
common/src/types/api-responses.ts
common/src/types/index.ts

This is a follow up PR to #359 to polish the code for `/Team` endpoint.
Resolves #279 
- Code Refactoring

Chore: Refactor team endpoint

---

api/src/app/index.ts
api/src/github/service.ts
api/src/team/controller.ts
api/src/team/repository.ts
common/src/types/api-responses.ts
common/src/types/index.ts
web/src/apps/main/components/card/index.tsx
web/src/apps/main/components/contributors/index.tsx
web/src/apps/main/components/dialog/index.tsx
web/src/apps/main/entry/app.tsx
web/src/apps/main/pages/team/catalog/index.tsx
web/src/apps/main/pages/team/index.tsx
web/src/apps/main/redux/actions/team-page/index.ts
web/src/apps/main/redux/index.ts
web/src/apps/main/redux/reducers/index.ts
web/src/apps/main/redux/reducers/team-page/index.tsx

Team page feature branch, resolves #279 
_please branch out of [`feature/team`](https://github.com/dzcode-io/dzcode.io/tree/feature/team) for any changes related to search implementation_

Feature: DzCode i/o Team

---

api/src/github/service.ts
api/src/github/types.ts
api/src/team/controller.ts
api/src/team/repository.ts
web/src/apps/main/components/card/index.tsx
web/src/apps/main/components/contributor-card/index.tsx
web/src/apps/main/components/contributors/index.tsx
web/src/apps/main/components/navbar/index.tsx
web/src/apps/main/pages/team/catalog/index.tsx
web/src/apps/main/pages/team/index.tsx
web/src/apps/main/redux/actions/projects-page/index.ts
web/src/apps/main/redux/actions/team-page/index.ts
web/src/apps/main/redux/reducers/index.ts
web/src/apps/main/redux/reducers/navbar-component/index.ts
web/src/apps/main/redux/reducers/team-page/index.tsx

This is a followup PR after #359 to refactor/clean the code for the `/Team` page, on both ends front and back.
- Refactoring

Chore: `/Team` code refactoring

---

api/nodemon.json
data/nodemon.json

Fixed a bug of typescript compilation in `./api` also `./data` on win32 platform.

Fix: tsc compilation bug on Windows for `./api` & `./data`

---

common/src/web/faq-data.ts
common/src/web/index.ts
mobile/__tests__/faq-test.tsx
mobile/src/redux/reducers/faq-screen/faq.ts
mobile/src/redux/reducers/faq-screen/index.ts
mobile/src/redux/reducers/index.ts
mobile/src/screens/articles/article-details/index.tsx
mobile/src/screens/faq/index.tsx
mobile/src/screens/faq/styles.ts
mobile/src/utils/link/index.ts

This PR is dedicated to add the FAQ screen to the mobile app.

Feature: Adding Frequently Asked Questions screen on mobile app

---

data/models/projects-v2/Weather_Forecast/info.json

- Added my weather forecast repository :)

added my weather forecast web app

---

data/models/projects-v2/Archiy_Package/info.json

add Archy Package on DZCODE.IO

---

data/models/projects-v2/Madinati_Meteo/info.json

(MadinaTeo) it's a weather web application simple and easy to use built with flask and OWM API.
Give it a try : https://madinateo.herokuapp.com/
* Built with:
Pure python backend ...
flask : a microframework for Python.
flask-wtf : forms extention for flask.
front-end : HTML5 , CSS3 , JS.
API used : openweathermap.org

MadinaTeo weather forcast

---

data/models/projects-v2/Godaddy_Reseller/info.json

bychis projects

---

data/models/projects-v2/Face_Mask_Detect/info.json

this is an open source Project made with keras and openCV for facial mask detection (Covid19).
every other contribution is welcome.

Face Mask Detection Project Added to DZCode

---

data/models/projects-v2/Godaddy_Reseller_Api_Client/info.json

Adding godaddy-reseller-api-client node package.
- I'm not sure

Adding godaddy-reseller-api-client project

---

.github/labeler.yml
.github/release.yml
api/package.json
common/package.json
data/package.json
mobile/app.json
mobile/package.json
package.json
web/package.json
yarn.lock

- fixed feature & project PR labels
- updated version of mobile app to `v3.0.4`
- added `syncpack` with `lint-staged`

Chore: dependency & versioning updates and labels fixes

---

mobile/src/entry/index.test.tsx
package.json

followup on #418 , added missing `lint-staged` script in root `package.json`, and while at it, i `yarn upgrade`d the dependencies
- refactoring/dependencies

Chore: root `lint-staged`

---

.github/workflows/cd.deploy.stg.yml
.github/workflows/cd.deploy.yml
.gitignore
package.json
packages/tooling/bundle-info.ts
web/package.json
web/src/apps/main/components/navbar/index.tsx
web/src/common/d.ts/__global.d.ts
web/webpack.config.ts

Show the currently deployed version of the website in the navbar
resolve #414 

Feature: show the current version of the website in navbar

---

mobile/babel.config.js
mobile/package.json
mobile/src/components/drawer-content/index.tsx
mobile/src/components/drawer-content/styles.ts
mobile/src/types/__global.d.ts

Show the currently deployed version of the mobile app in the navbar
part of #427 

Feature: show the current version of the mobile app in navbar

---

api/src/app/index.ts
api/src/app/middlewares/error.ts
api/src/app/middlewares/sentry-error-handler.ts
api/src/app/middlewares/sentry-request-handler.ts
api/src/logger/service.ts

Resolvse #428 first task
- Chore

Chore: capture full error object in error middleware using Sentry

---

.github/workflows/ci.main.yml
packages/ui/package.json
packages/ui/src/error-boundary/index.tsx
packages/ui/src/link/index.tsx
web/package.json
web/src/apps/main/entry/app.tsx
web/src/apps/main/entry/index.tsx
web/src/apps/main/pages/articles/index.tsx
web/src/apps/main/pages/contribute/index.tsx
web/src/apps/main/pages/faq/index.tsx
web/src/apps/main/pages/landing/index.tsx
web/src/apps/main/pages/learn/index.tsx
web/src/apps/main/pages/not-found/index.tsx
web/src/apps/main/pages/projects/index.tsx
web/src/apps/main/pages/team/index.tsx
yarn.lock

Render errors are now contained on the page level, thanks to [React Error Boundries](https://reactjs.org/docs/error-boundaries.html)
Resolves #428 

FEATURE: Setup React Error Boundaries in `./web`

---

.github/labeler.yml
.github/workflows/ci.pr.yml
README.md
api/src/app/endpoints.ts
mobile/app.json
mobile/src/components/try-again/index.tsx
mobile/src/redux/actions/articles-screen/index.ts
mobile/src/redux/actions/contribute-screen/index.ts
mobile/src/redux/actions/learn-screen/index.ts
mobile/src/redux/actions/projects-screen/index.ts
mobile/src/redux/reducers/articles-screen/index.ts
mobile/src/redux/reducers/contribute-screen/index.ts
mobile/src/redux/reducers/learn-screen/index.ts
mobile/src/redux/reducers/projects-screen/index.ts
mobile/src/screens/articles/article-details/index.tsx
mobile/src/screens/articles/articles-list/index.tsx
mobile/src/screens/contribute/index.tsx
mobile/src/screens/learn/document-details/index.tsx
mobile/src/screens/learn/documents-list/index.tsx
mobile/src/screens/projects/index.tsx
package.json
packages/utils/src/loadable/index.ts
web/src/apps/main/redux/actions/articles-page/index.ts

Show a UI when an error occurs in any of [`redux actions`](https://github.com/dzcode-io/dzcode.io/tree/main/mobile/src/redux/actions) in `./mobile`
Resolves #428 

FEATURE: Show `TryAgain` component when a loading error happens in `./mobile`

---

mobile/package.json
mobile/src/components/error-boundary/index.tsx
mobile/src/components/try-again/index.tsx
mobile/src/entry/index.tsx
mobile/src/redux/actions/articles-screen/index.ts
mobile/src/redux/actions/contribute-screen/index.ts
mobile/src/redux/actions/learn-screen/index.ts
mobile/src/redux/actions/projects-screen/index.ts
mobile/src/screens/articles/article-details/index.tsx
mobile/src/screens/articles/articles-list/index.tsx
mobile/src/screens/articles/navigation.tsx
mobile/src/screens/contribute/index.tsx
mobile/src/screens/faq/index.tsx
mobile/src/screens/learn/document-details/index.tsx
mobile/src/screens/learn/documents-list/index.tsx
mobile/src/screens/learn/navigation.tsx
mobile/src/screens/projects/index.tsx
yarn.lock

Render errors are now contained on the screen level, thanks to [React Error Boundries](https://reactjs.org/docs/error-boundaries.html)
Resolves #428 

FEATURE: Setup React Error Boundaries in `./mobile`

---

mobile/package.json
yarn.lock

Fixing a regression from #451, the fix is taken from https://github.com/expo/sentry-expo/issues/141

BUG: used the exposed `@sentry/react-native` from `sentry-expo`

---

data/models/articles/A_Friendly_Tool_For_React_Native_Projects/content.md

This PR is dedicated to update the `react-native-help-create` article for the [newest version](https://github.com/Omar-Belghaouti/react-native-help-create/releases/tag/2.3.1) of the package.
- I'm not sure

Article: update `react-native-help-create` article

---

.github/workflows/ci.pr.yml
data/models/projects-v2/who_want_to_millionaire/info.json

I added my react who want to be a millionaire multilingual react app 
I m hoping my project get added

commit my project  who want to be a milionaire

---

.github/workflows/ci.pr.yml
web/src/apps/main/entry/webpack.plugins.ts
yarn.lock

- added "DzCode i/o" to dynamic URLs for #457 

Feature: added "DzCode i/o" to dynamic URLs

---

package.json
web/webpack.config.ts
yarn.lock

- updated `caniuse-lite` (`browserlist` db)
- Chore

CHORE: updated caniuse-lite (browserlist db)

---

web/src/apps/main/components/navbar/index.tsx
web/src/apps/main/redux/reducers/settings/index.ts

We want to release everything except Localization because it's not ready yet...
- Chore

CHORE: commented out Localization UI

---

data/models/projects-v2/Algeria_Logos/info.json

this is a pull request to add a project I've made,
AlgeriaLogos, an [open source](https://github.com/aimen08/algerialogos) collection
of high quality, pixel-perfect Algerian
company logos for free use.
website: https://www.algerialogos.com/

Added Algeria Logos project

---

api/src/app/endpoints.ts
api/src/app/index.ts
api/src/app/types/legacy.ts
api/src/github/service.ts
api/src/github/types.ts
api/src/milestone/controller.ts
api/src/milestone/types.ts
packages/models/src/milestone/__snapshots__/index.spec.ts.snap
packages/models/src/milestone/index.spec.ts
packages/models/src/milestone/index.ts
packages/ui/package.json
packages/ui/src/circular-progress/index.tsx
packages/ui/src/milestones/index.tsx
web/package.json
web/src/apps/main/components/t/dictionary.ts
web/src/apps/main/pages/landing/index.tsx
web/src/apps/main/pages/landing/milestones/index.tsx
web/src/apps/main/redux/actions/landing-page/index.ts
web/src/apps/main/redux/reducers/landing-page/index.ts
yarn.lock

- Display dzcode roadmap on the landing page

Feat: Display dzcode roadmap

---

web/src/apps/main/redux/actions/articles-page/index.ts
web/src/apps/main/redux/actions/documentation-page/index.ts

Fix: Removed trailing slash from resource slug

---

api/src/app/index.ts

Fix: disallow only /docs api urls

---

api/src/app/index.ts
api/src/app/middlewares/robots.ts
web/src/redux/index.ts
web/src/utils/index.ts

did what I could for #486 
- chore

CHORE: cleaned up some todos

---

packages/ui/src/milestones/index.tsx

as per the title, to show progress on in-progress milestones that are not the current ones, such as [milestone/17](https://github.com/dzcode-io/dzcode.io/milestone/17)

Feat: show milestone progress for in-progress milestone

---

api/package.json
data/package.json
mobile/package.json
package.json
packages/models/package.json
packages/ui-mobile/package.json
packages/ui/package.json
packages/utils/package.json
yarn.lock

DX is kinda broken, as a result of regression from #493, I fixed it on #489, so I cherry-picked those commits from their, let's merge them first in `main`
- Bug fix / chore

Chore: replaced `ttsc` with `ts-patch`

---

mobile/package.json
mobile/src/screens/contribute/index.tsx
packages/ui-mobile/package.json
packages/ui-mobile/src/_test/setup.ts
packages/ui-mobile/src/bottom-sheet-scroll-view/index.test.tsx
packages/ui-mobile/src/bottom-sheet-scroll-view/index.ts
packages/ui-mobile/src/bottom-sheet/index.test.tsx
packages/ui-mobile/src/bottom-sheet/index.tsx
packages/ui-mobile/src/bottom-sheet/styles.ts

This PR is dedicated to migrate `@gorhom/bottom-sheet` from `./mobile` to `@dzcode.io/ui-mobile`
Resolves #508 

Feat: Migrate `@gorhom/bottom-sheet` to `@dzcode.io/ui-mobile`

---

packages/ui-mobile/src/_types/filter.ts
packages/ui-mobile/src/_types/option.ts
packages/ui-mobile/src/_types/project.ts
packages/ui-mobile/src/_types/route.ts
packages/ui-mobile/src/app-bar/index.tsx
packages/ui-mobile/src/bottom-sheet/bottom-sheet/index.tsx
packages/ui-mobile/src/card/contribute-card/index.tsx
packages/ui-mobile/src/card/project-card/index.tsx
packages/ui-mobile/src/drawer/drawer-content/index.tsx
packages/ui-mobile/src/error-boundary/index.tsx
packages/ui-mobile/src/filter/index.tsx
packages/ui-mobile/src/loading/index.tsx
packages/ui-mobile/src/markdown/index.tsx
packages/ui-mobile/src/navigation/drawer-nav/index.tsx
packages/ui-mobile/src/navigation/stack-nav/index.tsx
packages/ui-mobile/src/theme/index.ts
packages/ui-mobile/src/theme/style/color.ts
packages/ui-mobile/src/try-again/index.tsx

This PR is dedicated to add jsdoc for the `@dzcode.io/ui-mobile` package to enhance the developer experience by providing documentation for all related sources within the package.
Resolves
- #517 
- Documentation

Docs: Add jsdoc to `@dzcode.io/ui-mobile`

---

data/models/projects-v2/Leblad/info.json

This PR is dedicated to add [leblad](https://github.com/omdxp/leblad) go module project which is an implementation for [dzcode-io/leblad](https://github.com/dzcode-io/leblad) in Go language.
- Data

Data: Add `leblad` go module project

---

api/src/app/endpoints.ts
mobile/src/redux/actions/projects-screen/index.ts
packages/ui/src/_hooks/use-colors.ts
packages/ui/src/avatar/index.tsx
packages/ui/src/card/project/index.tsx
packages/ui/src/icon/contribution/index.tsx
web/src/pages/projects/index.tsx
web/src/redux/actions/projects-page/index.ts
web/src/redux/reducers/projects-page/index.ts

feat: show languages and contributors in project card

---

mobile/app.json
mobile/src/_entry/app.spec.tsx
mobile/src/_entry/app.tsx
mobile/src/redux/reducers/projects-screen/adapters/projects.ts
mobile/src/screens/articles/article-details/index.tsx
mobile/src/screens/articles/article-details/styles.ts
mobile/src/screens/contribute/index.tsx
mobile/src/screens/learn/document-details/index.tsx
mobile/src/screens/projects/index.tsx
packages/ui-mobile/src/avatar/avatar-group/index.test.tsx
packages/ui-mobile/src/avatar/avatar-group/index.tsx
packages/ui-mobile/src/avatar/avatar-group/styles.ts
packages/ui-mobile/src/avatar/avatar/index.test.tsx
packages/ui-mobile/src/avatar/avatar/index.ts
packages/ui-mobile/src/card/contribute-card/index.test.tsx
packages/ui-mobile/src/card/contribute-card/index.tsx
packages/ui-mobile/src/card/contribute-card/styles.ts
packages/ui-mobile/src/card/project-card/index.test.tsx
packages/ui-mobile/src/card/project-card/index.tsx
packages/ui-mobile/src/card/project-card/styles.ts
packages/ui-mobile/src/markdown/index.tsx
packages/ui-mobile/src/theme/index.ts

This PR is dedicated to update the current mobile UI design to the latest one in the web.
Resolves
- #543 
- Chore

chore: Mobile UI Design parity with web for mobile

---

api/src/contribution/repository.ts
api/src/fetch/service.ts
api/src/github/service.ts
api/src/project/controller.ts
api/src/team/repository.ts
data/models/projects/Mishkal/info.json

bugfix: all GitHub related api endpoints fails when GitHub service fails

---

api/oracle-cloud/deploy.ts
api/oracle-cloud/docker-compose.yml

- new VPSs
- refreshed ssh keys
- tweaked deployment script to use `opc` instead of `root` user
- updated DNS config for `api-stage.` and `api.`

Update deployment script and docker-compose file

---

data/models/projects/AlgeriansCoinsObjectDetection/info.json

Algerians coins object detection using the pre-trained model YOLOv8 and a dataset of 250 images of coins.

Add project: Algerians Coins Object Detection

---

data/models/projects/Leblad/info.json

Adding [leblad-rs](https://github.com/omdxp/leblad-rs) project.

add leblad-rs project

---

data/models/projects/System_Monitor/info.json

added https://github.com/ZibanPirate/sysmon

Added System Monitor project

---

data/models/projects/Fun/info.json

Adding [fun](https://github.com/omdxp/fun) project so devs can help out.

add fun project

---

data/models/projects/Courier_Dz/info.json

Thank you for considering my project.
> CourierDZ is a PHP client designed to simplify the integration of Algerian shipping providers into your applications.

[ New Project ] : add CourierDZ is a PHP client Project

---

api/src/app/endpoints.ts
api/src/contributor/controller.ts
api/src/contributor/repository.ts
api/src/contributor/types.ts
api/src/project/repository.ts
web/cloudflare/functions/w/contributors-sitemap.xml.ts

forgot to generate the sitemap for contributor page, following up after #610

feat: sitemap for contributors pages

---

api/src/app/endpoints.ts
api/src/contribution/controller.ts
api/src/contributor/controller.ts
api/src/github/controller.ts
api/src/milestone/controller.ts
api/src/project/controller.ts
api/src/search/controller.ts
web/src/components/locale/dictionary.ts
web/src/redux/actions/contribution.ts
web/src/redux/actions/contributions.ts
web/src/redux/actions/contributor.ts
web/src/redux/actions/contributors.ts
web/src/redux/actions/milestones.ts
web/src/redux/actions/project.ts
web/src/redux/actions/projects.ts
web/src/utils/search.ts

Chore: lowercased urls

---

api/db/migrations/0007_rich_trauma.sql
api/db/migrations/meta/0007_snapshot.json
api/db/migrations/meta/_journal.json
api/src/_utils/hash.ts
api/src/ai/repository.ts
api/src/ai/service.ts
api/src/ai/table.ts
api/src/digest/cron.ts
packages/models/src/ai-prompt/index.ts

_part 3 of 3_
_verify here: https://stage.dzcode.io/ar/contribute_
_deployed stage code is from this PR_
- added AIService repository, to cache ai prompts
- enhanced Arabic translation for project.name and contribution.title

Feat: cache ai prompt

---

data/models/projects/Satim_Php/info.json

Thank you for considering my project.
> PHP package for seamless integration with Satim.dz, the official interbank payment gateway in Algeria.
https://github.com/PiteurStudio/satim-php

New Project: add Satim PHP Client Project

---

data/models/projects/Algerian_Administrative_Division/info.json

**Title:** New Project: Laravel Package for Algerian Administrative Data  
**Description:**  
Introducing another Laravel Algerian Cities package by [Kouceyla](https://github.com/kossa)
🔗 https://github.com/kossa/algerian-cities
This package has been around since 2020 and continues to receive updates. I believe it would be a great addition to **dzcode** (Algerian Administrative Division) to improve visibility. It already has **5 contributors** worked on it.

New Project: Another package to interact with Algerian administrative

---

.github/workflows/ci.pr.yml

fix: change pull request trigger to pull_request_target for CI workflow

---

data/models/projects/Open_listings/info.json
data/models/schemas/project.json

Hi, 
Thank you for your attention. this pull request adds open-listings-dz (swag-dz).

add open-listings-dz (swag-dz) project

---

data/models/projects/Khadra_Project/info.json

Add khadra project

---

data/models/documentation/About_dzcode_io/Add_Your_Project_To_dzcode_io/content.md

to avoid misleading new contributors such [as this one](https://github.com/dzcode-io/dzcode.io/pull/658/files#diff-bc2bbb26e254b185afca50be619fd6d68f1187871532d0d8378d866702110185R7)

Rename repository field to name in projects.json
