dzcode-io/dzcode.io

frontend/package.json, frontend/webpack.config.js
fix Windows development environment. by : 
- modify the path of the bundle in Webpack.
- added cross-env to production, 
Fixes #39 
- [ x ] Affected `frontend`
=> fix windows yarn dev

data/src/utils/data.ts
Fixed bug where Data generation breaks when there is no content.md file
=> 🐞 fix: data generation breaks when no content

frontend/src/apps/main/entry/webpack.plugins.js
Fixed bug where /Learn urls are not properly SSRenderd
=> 🐞 fixed learn URLs SSR bug

frontend/src/apps/main/scenes/learn/index.tsx, frontend/src/apps/main/scenes/learn/sidebar/index.tsx
Properly select the right item on sidebar
=> 🍔 Properly select the right item on sidebar

.github/workflows/cgl-data.yml, .github/workflows/cgl-frontend.yml, .github/workflows/cgl-fullstack.yml
Annoying Warnings are now hidden in CI logs, only error are shown
=> ⚠️ warnings are now hidden from CI output

data/models/projects/React_Native_Currency_Converter/info.json
i've did a small mistake , adding my open source project link in the wrong format that cause to redirect user to wrong link : https://github.com/https://github.com/ilies-space/currency_converter_rn .
now i have deleted the ("https://github.com/") from the info.json/githubURI
and that will fix the problem .
Thank you
=> fixing githubURI project wrong format

data/models/articles/A_Python_Website_No_Framework_Needed/content.md, data/models/articles/A_Python_Website_No_Framework_Needed_PART_2/content.md, data/models/articles/Open_source/content.md, data/models/articles/Send_Emails_With_Django_and_Gmail_A_Better_Way/content.md, data/models/articles/Use_Conventional_Commits_To_Contribute_To_DZCode/content.md, data/models/articles/top-articles.json
as a followup to #260 , now there is no need to add a social footer in `content.md`, as it now on the **Authors** section on the bottom
=> removed social footer from content

web/src/apps/main/components/markdown/index.tsx, web/src/apps/main/components/theme/palettes/dark.ts, web/src/apps/main/components/theme/palettes/light.ts
Fix the scrollbar issue #267  on dark mode
scrollbar becomes bold and sticky on dark mode, the issue appears due to including the field  `mode` on `PaletteOptions`  which is not defined in the interface.
=> Remove "mode" from PaletteOptions

web/webpack.config.js
path.join() adds "\" in URLs in  windows  machines which leads into unclear errors.
its fixed by hard coding the join of urls.
=> - Fixed path.join() erros in webpack config

api/src/app/controllers/github/index.ts, api/src/app/index.ts, api/src/app/routes/api/github/index.ts, api/src/app/services/github/index.ts, api/src/github-user/controller.ts, api/src/github-user/types.ts, api/src/github/dto.ts, api/src/github/service.ts, api/src/github/types.ts, api/test/mocks.ts, common/src/types/index.ts, web/src/apps/main/redux/actions/articles-page/index.ts, web/src/apps/main/redux/actions/documentation-page/index.ts
Implements #286
- Call `v2/GithubUsers/{username}` from the frontend
- Remove the old API `/github/users`
=> migrate new GitHub users API

web/.prettierignore, web/jest.config.js, web/package.json, web/src/apps/main/components/footer/__snapshots__/footer.spec.tsx.snap, web/src/apps/main/components/footer/footer.spec.tsx, web/src/apps/main/components/footer/index.tsx, web/src/apps/main/pages/faq/__snapshots__/index.int.spec.tsx.snap, web/src/apps/main/pages/faq/index.int.spec.tsx, web/src/apps/main/pages/faq/index.tsx, web/tsconfig.json, yarn.lock
Added first unit tests for footer component, and first integration test for faq page
part of #298 
=> Added first unit and integration tests

.github/CONTRIBUTING.md, README.md, data/models/projects/ReadMe.md
In the repo still there are some words left from the old branch naming convention, this PR ensures that we use "main" instead as the main branch everywhere in the repo.
=> changed "master" keyword to "main" everywhere in the repo

mobile/.eslintrc.js, mobile/babel.config.js, mobile/package.json, mobile/src/components/shared/app-bar.tsx, mobile/src/screens/navigation.tsx, yarn.lock
with this change, we don't need to write pop-validation, as it will be written automatically with the babel-plugin `babel-plugin-typescript-to-proptypes`
fixes #343 
- refactoring
=> Chore: auto validate prop-types using TS

package.json, yarn.lock
after adding sentry to both web and mobile, yarn workspace hoisting caused problems due to different versions of the sentry client on both web and mobile.
this PR fixes this issue, reported in https://github.com/dzcode-io/dzcode.io/runs/3316195426
=> FIX: don't hoist web folder

mobile/.eslintignore, mobile/.gitignore, mobile/.prettierignore, mobile/package.json, mobile/src/config/index.ts, mobile/src/redux/actions/articles-screen/index.ts, mobile/src/redux/actions/contribute-screen/index.ts, mobile/src/redux/reducers/articles-screen/index.ts, mobile/src/redux/reducers/contribute-screen/index.ts, mobile/src/screens/articles/article-details/index.tsx, mobile/src/screens/contribute/card-item/index.tsx, mobile/src/utils/fetch/endpoints.ts, mobile/src/utils/fetch/index.ts
A third round of refactoring that resolves #362 , which adds a typed wrapper around `fetch`. Also renamed the auto-generated `.common` folder  to `_common` due to caching problems with Metro
- Refactoring
=> Chore: mobile code cleanup 3

package.json, packages/models/src/language/index.spec.ts
turns out the lint-staged was ignored since #424 , this should fix that
=> Fix: use `exec` instead of `run` when running `lint-staged`

.github/workflows/cd.deploy.stg.yml, .github/workflows/cd.deploy.yml, api/package.json, api/src/app/index.ts, web/package.json, web/webpack.config.ts, yarn.lock
Google is indexing the staging version of the website:
These changes will tell google or any agent to not index any version of dzcode.io other than the production one.
=> Fix: Added robots.txt to disallow indexing non production version of the website

mobile/package.json, mobile/src/screens/articles/article-details/index.tsx, mobile/src/screens/learn/document-details/index.tsx, packages/ui-mobile/package.json, packages/ui-mobile/src/loading/index.tsx, packages/ui-mobile/src/markdown/index.test.tsx, packages/ui-mobile/src/markdown/index.tsx, yarn.lock
This PR is dedicated to migrate `react-native-markdown-display` from `./mobile` to `@dzcode.io/ui-mobile`
Resolves #505 
=> Feat: Migrate `react-native-markdown-display` to `@dzcode.io/ui-mobile`

.github/labeler.yml
This PR is dedicated to add the `ui-mobile` label in CI automatically whenever change happens to `./packages/ui-mobile`
Resolves #515 
=> Chore: add `ui-mobile` label to `labeler.yml`

packages/ui/src/v2/dropdown/index.tsx, web/src/_entry/app.tsx
fixed two bugs:
- closing the theme dropdown without selecting a theme will cause the them to revert to light and the dropdown to have no theme selected.
- landing page header text is not center-aligned vertically when switching to Arabic
these are regressions of #489 
=> Fix: landing page UI migration bugs

api/src/app/index.ts, api/src/contribution/repository.ts, api/src/contributor/controller.ts, api/src/data/service.ts, api/src/data/types.ts, api/src/github/service.spec.ts, api/src/github/service.ts, api/src/github/types.ts, api/src/milestone/controller.ts, api/src/project/controller.ts, api/src/project/types.ts, api/src/team/repository.ts, packages/models/src/contributor/__snapshots__/index.spec.ts.snap, packages/models/src/contributor/index.spec.ts, packages/models/src/project-reference/index.ts, packages/models/src/project/index.ts, packages/models/src/repository-reference/index.ts, packages/models/src/repository/__snapshots__/index.spec.ts.snap, packages/models/src/repository/index.spec.ts, packages/models/src/repository/index.ts
added a new endpoint in `./api`, that returns the projects listed under dzcode and display more info for each project such as contributors ...etc
you can test it by:
```sh
curl -X 'GET' \
'http://localhost:7070/Projects/' \
-H 'accept: text/html; charset=utf-8'
```
or by visiting:
http://localhost:7070/docs/#/Project/ProjectController.getProjects
=> feat: move projects endpoint from `./data` to `./api`

README.md, api/src/app/endpoints.ts, api/src/app/index.ts, api/src/article/controller.ts, api/src/article/types.ts, api/src/data/service.ts, api/src/data/types.ts, mobile/src/redux/actions/articles-screen/index.ts, mobile/src/redux/reducers/articles-screen/adapters/articles.ts, mobile/tsconfig.json, packages/models/src/article/__snapshots__/index.spec.ts.snap, packages/models/src/article/index.spec.ts, packages/models/src/article/index.ts, packages/models/src/contributor/index.ts, packages/models/src/repository/index.ts, web/src/redux/actions/articles-page/index.ts, web/src/redux/actions/documentation-page/index.ts
=> feat: move articles endpoint from `./data` to `./api`

api/src/fetch/service.ts, api/src/project/controller.ts, packages/utils/src/concurrency/index.ts
and made `/project` endpoint fail gracefully when rich info fetching fails.
the bug was caused by a duplicate delete statement [here](https://github.com/dzcode-io/dzcode.io/pull/581/files?diff=unified&w=1#diff-c87f7bb1e49f256f08c6865cbbbb55660edd0f8667f0c91023f5c9d896287b71L66), that keeps eating the queue 2x faster, therefor when we have two parallel fetches, the last added fetch request never get fulfilled because it was deleted from the queue before it was processed. fixed in a9ee14372ce6aa34a87b6faae4fa20f6940dc6dd
=> Fixed bug where projects endpoint stuck

api/src/contribution/controller.ts, api/src/contribution/repository.ts, api/src/contribution/types.ts, packages/models/src/contribution/__snapshots__/index.spec.ts.snap, packages/models/src/contribution/index.spec.ts, packages/models/src/contribution/index.ts
[/Contribute](https://www.dzcode.io/Contribute) page is spammed with cards that are created by bots.
- added `createdBy` to `Contribution` model, that reference an `Account` Model
- we use it, to filter out bot users, when calling `contributionRepository.find`
test:
- [dzcode.io/Contribute](https://www.dzcode.io/Contribute) should still show bot contributions
- [stage.dzcode.io/Contribute](https://stage.dzcode.io/Contribute) won't show bot contributions
=> Fix: filtering out contributions created by bots

.github/workflows/cd.deploy.stg.yml, .github/workflows/cd.deploy.yml, .github/workflows/ci.reusable.lighthouse.yml, .gitignore, README.md, api/oracle-cloud/deploy.ts, api/oracle-cloud/docker-compose.yml, api/oracle-cloud/nginx.conf, package-lock.json, packages/tooling/.prettierignore, web/lighthouserc.cjs, web/package.json
- run lighthouse on our pages in all languages, and store the scores in our selfhosted server.
- lighthouse results are in: [lh.dzcode.io](https://lh.dzcode.io/) and [lh-stage.dzcode.io](https://lh-stage.dzcode.io/)
=> feat: Lighthouse setup

.github/release-drafter.yml, .github/workflows/cd.deploy.stg.yml, .github/workflows/ci.hourly.yml, .github/workflows/ci.reusable.lighthouse.yml
Hourly cron job that measures lighthouse score on pages of dzcode.io and stage.dzcode.io, we can then see the progress of the score over time while we work on #302 
- prd: https://lh.dzcode.io/app/projects/dzcode.io/dashboard?runUrl=https://www.dzcode.io/contribute/
- stg: https://lh-stage.dzcode.io/app/projects/dzcode.io/dashboard?runUrl=https://stage.dzcode.io/contribute/
=> feat: Hourly metrics

web/package.json, web/src/_build/gen-multiple-htmls.ts, web/src/_build/gen-robots-txt.ts, web/src/_build/pages/static-pages.ts
serve 404.html for not found links
=> fix: Cloudflare 404 redirect

README.md, api/docker-compose.yml, api/package.json, api/src/app/index.ts, api/src/config/types.ts, api/src/search/controller.ts, api/src/search/service.ts, api/src/search/types.ts, package-lock.json
Adding MeiliSearch docker image with a service
=> Add MeiliSearch service

.gitignore, README.md, api/docker-compose.yml, api/oracle-cloud/docker-compose.yml, api/package.json, api/src/app/index.ts, api/src/search/service.ts, api/src/search/types.ts
- Instantiating the MeiliSearch client with the necessary indexing during the `SearchService` instantiation.
- Add `index` service method to save new entries with their specific indexes.
=> Create MeiliSearch Indexes

api/src/app/index.ts, api/src/contributor/table.ts, api/src/digest/cron.ts, api/src/project/table.ts, api/src/search/service.ts, api/src/search/types.ts, packages/models/src/_base/index.ts
- Add `deleteAllDocuments` search service method.
- Index models that represent the contributions, contributors and projects.
=> Indexing models during cron job

api/package.json, api/src/app/index.ts, api/src/config/types.ts, api/src/digest/cron.ts, api/src/search/service.ts, data/package.json, packages/models/package.json, packages/tooling/.prettierignore, packages/tooling/package.json, packages/utils/package.json, web/package.json
added `--` to forward params inside to prettier
=> fix: prettier cli params were not passed correctly

api/src/search/controller.ts, api/src/search/service.ts, api/src/search/types.ts
- Add `GET /Search?query=some` endpoint.
- Impl search method.
=> Search Endpoint

api/src/app/endpoints.ts, api/src/contribution/controller.ts, api/src/contribution/repository.ts, api/src/contribution/types.ts, web/cloudflare/functions/ar/contribute/[slug].ts, web/cloudflare/functions/contribute/[slug].ts, web/cloudflare/functions/w/contributions-sitemap.xml.ts, web/cloudflare/handler/contribution.ts, web/src/_entry/app.tsx, web/src/components/contribution-card.tsx, web/src/components/locale/dictionary.ts, web/src/components/project-card.tsx, web/src/components/search.tsx, web/src/pages/contribute/contribution/index.tsx, web/src/redux/actions/contribution.ts, web/src/redux/slices/contribution-page.ts, web/src/redux/store.tsx
- contribution details page (for now it display the same contribution card UI)
- Open-graph metadata for the contribution page, eg: https://stage.dzcode.io/contribute/Switching-languages-does-not-work-properly-github-2758805285
- sitemap for all contribution page links: https://stage.dzcode.io/w/contributions-sitemap.xml
=> Feat: contribution page

data/models/projects/hey-cli/info.json
added https://github.com/ZibanPirate/hey-cli
=> feat: added hey cli project

packages/tooling/prune-dictionary.ts, web/package.json, web/src/components/locale/dictionary.ts
=> Chore: prune dictionary

web/cloudflare/handler/contribution.ts, web/cloudflare/handler/contributor.ts, web/cloudflare/handler/project.ts, web/src/_build/gen-multiple-htmls.ts, web/src/_build/pages/index.ts, web/src/_build/pages/template-pages.ts, web/src/_entry/index.html, web/src/pages/contribute/contribution/index.tsx, web/src/pages/contribute/index.tsx, web/src/pages/projects/project/index.tsx, web/src/utils/contribution.ts
part of https://github.com/dzcode-io/dzcode.io/issues/302
=> Fix: set canonical url

web/src/redux/actions/settings.ts
=> Fix switching languages at root

api/README.md, api/oracle-cloud/deploy.ts, api/package.json, api/src/ai/service.ts, api/src/config/types.ts, api/src/digest/cron.ts, api/src/digest/dto.ts, api/src/fetch/service.ts, api/src/fetch/types.ts, package-lock.json, web/src/components/contribution-card.tsx, web/src/components/project-card.tsx, web/src/pages/contribute/contribution/index.tsx
_part 2 of 3_
_verify here: https://stage.dzcode.io/ar/contribute_
_deployed stage code is from #634_
- added AIService
- used AIService to translate localized fields in during corn job
- removed hard-coded `dir="LTR"` values in `./web`
=> Feat: translate name and title fields using llm

.github/workflows/ci.reusable.misc.yml, web/cloudflare/functions/w/contributions-sitemap.xml.ts, web/cloudflare/functions/w/contributors-sitemap.xml.ts, web/cloudflare/functions/w/projects-sitemap.xml.ts, web/cloudflare/package.json, web/cloudflare/scripts/generate-config.ts
sitemap endpoints are failing because of a regression from #632.
endpoints such as
- https://www.dzcode.io/w/contributors-sitemap.xml
- https://stage.dzcode.io/w/contributors-sitemap.xml
Also added a CI check to make sure `web/cloudflare` builds successfully
=> fix: broken cloudflare worker builds

web/src/components/top-bar.tsx
**The bug:**
clear the cookie and load the website on a system that has light theme preferred
**Expected:**
you should get light mode
**Actual:**
you get dark mode
**Fix:**
when loading the theme from cookie, if no theme is found, try detecting user-prefered theme, and then fallback to dark mode
**NOTE**
also changed the code a bit, to allow for non-binary options, like having a thrid `auto-detect` option, or other theme names
=> fix: fallback to user prefered mode instead of assuming dark mode for first-time theme load

api/oracle-cloud/deploy.ts, api/src/bitbucket/types.ts
because our weak VPS can not handle the load of running containers and building new ones at the same time
this issue was causing deployment failure.
NOTE: this workaround has the downside of having a few minutes of downtime
deployment went smoothly here:
https://github.com/dzcode-io/dzcode.io/actions/runs/14419466405/job/40440249143
=> fix: take down running containers before building

data/models/projects/plugbrain/info.json
Add PlugBrain, an opensource Android app for focus and distraction control using mental math challenges.
=> Add the PlugBrain Android app
